Makefile.am, fdt.c++, fdt.h++, freedom-mee_header-generator.c++, libfdt.h++, tests/hifive1-ldscript.bash, tests/hifive1-makeattributes.bash, tests/hifive1-mee_header.bash, tests/hifive1-openocd.bash, tests/hifive1.dts
The HiFive1 has a more complicated clocking system that the QEMU and
FPGA targets do.  This commit allows the MEE header file generator to
generate enough information to inform the MEE about these nested
clocking systems.
The actual generated output is now very tightly coupled to the MEE
implementation, which isn't ideal.  I'm not sure quite how else to deal
with this, though.
There's an additional test set that targets the HiFive1 device tree that
we're actually going to send out (or at least, close to it).
=> freedom-mee_header-generator: Handle multiple clocks

Makefile.am, freedom-ldscript-generator.c++, freedom-mee_header-generator.c++, tests/e31-eval-ldscript.bash, tests/e31-eval-makeattributes.bash, tests/e31-eval-mee_header.bash, tests/e31-eval-openocd.bash, tests/e31-eval.dts
The simulation RTL targets have slightly different behavior than the ASICs:
* There's no emulated SPI flash, instead there's a magic memory.
* There's a quick test finisher to get some simple data out of the simulation about the correctness of a given test.
=> Add support for RTL emulation machines

Makefile.am, fdt.c++, fdt.h++, freedom-ldscript-generator.c++, freedom-mee_header-generator.c++, tests/e51-arty-ldscript.bash, tests/e51-arty.dts
This respects #address-cells and #size-cells to determine the number of
cells in a target address or size field.  It also splits 'target_long'
into 'target_addr' and 'target_size' to respect the difference.
=> Support designs with 64-bit addresses or sizes

Makefile.am, freedom-ldscript-generator.c++, tests/e31-bigmem-ldscript.bash, tests/e31-bigmem-makeattributes.bash, tests/e31-bigmem-mee_header.bash, tests/e31-bigmem-openocd.bash, tests/e31-bigmem.dts, tests/e31-eval-ldscript.bash, tests/multi-e31-arty-ldscript.bash
This pull request contains three fixes to testram-based systems:
* When a system has a testram everything should be placed in there.
* The testram should be called "ram", not "flash".
* The stack can't be more than 2GiB away from the startup code as otherwise the address can't be loaded.  There's a hack for this one :).
=> A pair of testram-based fixes

freedom-mee_header-generator.c++
The PLL constructor requires additional fields to be generated in the
header file
Signed-off-by: Nathaniel Graff <nathaniel.graff@sifive.com>
=> Add header generation for FE310-G000 PLL init

freedom-zephyrdtsfixup-generator.c++
Zephyr dts.fixup alias for setting the baud rate of the UART
=> Add CURRENT_SPEED define for UARTs

fdt.c++, freedom-ldscript-generator.c++, tests/e31-eval.dts, tests/hifive1.dts
These entries can be generated along with the hardware and deprecate the "sifive,testram0" entries that we used to have to manually add.
=> Support "sifive,periph-port" and "sifive,sys-port" entries

.gitignore, Makefile.am, freedom-mee_specs-generator.c++, tests/hifive1-mee_specs.bash
riscv64-sifive-elf-gcc needs additional specs files to be provided by
the environment in order to correctly select various libraries and
headers.  This tool currently uses a pretty bruce-force approach to
generating the specs file where it depends on all sorts of nastiness
like the GCC multilib paths, tuple name, and version number.
=> mee_specs-generator: New tool

Makefile.am, freedom-makeattributes-generator.c++, freedom-mee_specs-generator.c++, multilib.h++, tests/e34-eval-ldscript.bash, tests/e34-eval-makeattributes.bash, tests/e34-eval-mee_header.bash, tests/e34-eval-mee_specs.bash, tests/e34-eval-openocd.bash, tests/e34-eval.dts
The default set of multilibs on RISC-V GCC implementations doesn't
include a sane setting for rv32imafdc/ilp32.  While this is arguably a
bug (it could be implemented with the rv32imac/ilp32 library), it's also
probably best to be mapping these to rv32imafdc/ilp32f as users probably
want to take advantage of their F registers when calling functions.
In the long run we should fix the multilib generator to provide a
complete set of multilibs, but for now we'll have to live with these
lookup tables.
=> Add support for rv32imafdc cores

Makefile.am, freedom-ldscript-generator.c++, tests/e31-eval-simple_bus-ldscript.bash, tests/e31-eval-simple_bus-makeattributes.bash, tests/e31-eval-simple_bus-mee_header.bash, tests/e31-eval-simple_bus-openocd.bash, tests/e31-eval-simple_bus.dts
This is a bit of a hack, but we have some device trees floating around
that don't have proper device tree entries for their test memories.
Matching on simple-bus alone isn't enough, as we really need to only
look for empty simple busses, but we should be able to get away with
this for now.
=> If there is no explicit external bus then match simple-bus

freedom-zephyrdtsfixup-generator.c++
Update to accommodate changes requested while upstreaming the RISC-V support into Zephyr
=> Fixes for the Zephyr dts.fixup generator

freedom-mee_specs-generator.c++
The spec files we generated didn't respect some of the standard GCC arguments.  The specific one that brought this to my attention was the missing support for `-T`, but I found a few more as I poked around the code.
=> mee_specs-generator: Add support for the "-nostartfiles", "-nostdlib", and "-T" GCC arguments

freedom-ldscript-generator.c++
Code in `.itim` and `.itim.*` will be linked into the memory provided by the ITIM, if one exists.
Provides the symbols:
- mee_segment_itim_source_start
- mee_segment_itim_target_start
- mee_segment_itim_target_end
for `crt0.S` to copy the ITIM sources from flash/ram into the ITIM at boot.
=> Add linker support for ITIM

metal_header/sifive_spi0.h
Increment the counter so that we close the array definition with '};'.
=> Fix SPI device handle array

Makefile.am, freedom-ldscript-generator.c++, metal_header/device.c++, metal_header/fixed_factor_clock.h, metal_header/freedom-metal_header-generator.c++, metal_header/riscv_clint0.h, metal_header/riscv_cpu.h, metal_header/riscv_cpu_intc.h, metal_header/riscv_plic0.h, metal_header/sifive_global_external_interrupts0.h, metal_header/sifive_local_external_interrupts0.h
Depends on #64 
PR contains:
- Rename CPU interrupt controllers to cpu_<number>_interrupt_controller to allow multiple to be instantiated
- Support multiple parent interrupts for PLIC and CLINT
- Add a binding for fixed-factor-clock (for HiFive Unleashed)
- Allocate multiple stacks and provide __stack_size as a symbol for the C environment
- Assorted additional fixups for multiple CPU nodes
=> Multicore Support

bare_header/freedom-bare_header-generator.c++, freedom-ldscript-generator.c++, freedom-makeattributes-generator.c++, metal_header/freedom-metal_header-generator.c++, metal_header/sifive_global_external_interrupts0.h, metal_header/sifive_local_external_interrupts0.h, multilib.h++, tests/e34-eval-makeattributes.bash, tests/e34-eval-metal_specs.bash
This PR disable the release tag and timestamp update to generated files.
Release tag will only be added if -r "Tag Label" is given.
While at it also fix a bug in Global and Local External interrupts inline uncover during spanning config testing.
=> Add Release Tag and timestamp during release time

bare_header/freedom-bare_header-generator.c++, metal_header/freedom-metal_header-generator.c++
If the program gets a full path to its output file, only include the filename and its containing folder in the beginning ifndef/define.
=> Don't include full output file paths in ifdefs

freedom-ldscript-generator.c++
Reverts sifive/freedom-devicetree-tools#89
=> Revert "Check first for the presence of a memory node"

multilib.h++
Adds support for
- rv32ec
- rv32ic
- rv64ic
Also adds ISA subsets are not currently represented by multilibs, mapped
to supported march/mabi pairs.
Includes:
- rv32imf -> rv32im/ilp32
- rv64imf -> rv64im/lp64
=> Add additional supported ISA extension subsets

bare_header/freedom-bare_header-generator.c++, metal_header/freedom-metal_header-generator.c++
Compilation succeeds on ubuntu 16.04 but fails on mac os due to missing headers. Including `sstream` fixes it for me.
=> include sstream in files that use istringstream

build.wake
- add `runFreedomBareHeaderGenerator` for generating the platform header
- update `makeFreedomBSP` to include platform header
- tweaks to job inputs to prevent unnecessary rebuilds
=> update wake rules for new BSP

freedom-openocdcfg-generator.c++
Only require 1 sram to alias it to ram
=> Fix OpenOCD config generator on e20 arty

multilib.h++
Adds the ISA mapping
- rv32ea -> rv32e
- rv32ia -> rv32i
- rv64ia -> rv64i
=> Add support for atomic-only ISA extension

metal_header/fixed_clock.h
Fixes discarded const qualifier warning
=> Make argument to __metal_driver_fixed_clock_rate const

freedom-ldscript-generator.c++
This fixes loads and stores when initializing the data, bss, and itim sections in libgloss' _start on 64-bit targets.
=> Fix alignment issues on 64-bit targets

linker_script/strategies/default_bullet_arty.c++, linker_script/strategies/default_bullet_strategy.c++
Some targets identify their ITIM with the compatible string "sifive,sram0".
=> Also use sifive,sram0 for ITIM in targets with a memory port

bare_header/sifive_fu540_c000_l2.h, metal_header/sifive_fu540_c000_l2.c++
These patches contain generating control_base functions of l2 cache controller and modifying the name of compatible. The compatible of cache controller of design.dts in bsp should be corrected together.
=> Fix l2 cache controller issue

metal_header/riscv_cpu.c++, metal_header/riscv_plic0.c++
In some functions of CPU and PLIC, the if-else condtion was duplicated, such as 'idx == 0' be checked twice.
=> Fix duplicated index for filter condition

freedom-ldscript-generator.c++
This makes sure that early_trap_vector is in the ROM and not in the ITIM
=> Link everything in .text.metal.init.* into .init

bare_header/device.c++
Also extract "control" named registers
=> Fix base address extraction in bare header generator

bare_header/device.c++
This results in bare_header preferring the control registers if they are
available in the devicetree, which was necessary to extract the correct
SPI base register and size.
=> Swap order of control and mem register extraction

metal_header/riscv_clint0.c++, metal_header/riscv_cpu.c++, metal_header/riscv_plic0.c++
In some functions of CPU and PLIC which generated in the metal.h  header file, the if-else condtions are duplicated such as 'idx == 0'  be checked twice.
In PLIC generator, don't use 'else-if' conditional to filter the max_interrupts condition. It causes dosen't generate tail curly brackets when the value of interrupts-extended property specifying only one contexts.
In CPU generator, don't use 'else-if' conditional to filter the num_cpus condition. It causes dosen't generate tail curly brackets when there is only one cpu node in dts.
There is also a potential bug in clint, I fix it in the riscv_clint.c++ together at this time
=> Fix duplicated idx v2

linker_script/section.c++, linker_script/section.h, linker_script/sections/data_group.c++, linker_script/sections/itim_group.c++, linker_script/sections/itim_text_group.c++, linker_script/sections/uninit_group.c++
Instead of hoping that the target and source symbols for the beginning
of the data, itim, and bss sections match, explicitly set them to the
LOADADDR and ADDR of the section. This fixes bugs where the linker
decided that, for example, metal_segment_data_source_start doesn't have
to match exactly the load address of the data segment, causing corrupted
data in the running program.
=> [19.08 Backport] Fix target/source symbols for data, itim, bss

linker_script/section.c++, linker_script/section.h, linker_script/sections/data_group.c++, linker_script/sections/itim_group.c++, linker_script/sections/itim_text_group.c++, linker_script/sections/uninit_group.c++
Instead of hoping that the target and source symbols for the beginning
of the data, itim, and bss sections match, explicitly set them to the
LOADADDR and ADDR of the section. This fixes bugs where the linker
decided that, for example, metal_segment_data_source_start doesn't have
to match exactly the load address of the data segment, causing corrupted
data in the running program.
=> Fix target/source symbols for data, itim, bss

linker_script/sections/data_group.c++
If the RodataGroup is included first in the layout, then the rodata
sections will still be put in .rodata instead of .data. This makes sure
that the read-only data is still included in ramrodata layouts.
=> Ask for rodata in data section

linker_script/sections/data_group.c++
If the RodataGroup is included first in the layout, then the rodata
sections will still be put in .rodata instead of .data. This makes sure
that the read-only data is still included in ramrodata layouts.
=> [19.08 Backport] Ask for rodata in data section

metal_header/stdout_path.c++
If no stdout-path baud rate is requested, assume 115200.
=> Set default stdout-path baud rate to 115200

scripts/autoconf_wrapper
Don't run `autoreconf -i` since the output of autotools is already checked in.
=> remove autoreconf from autoconf_wrapper script

bare_header/riscv_plic0.h, metal_header/riscv_plic0.c++, tests/e51-arty.dts
Add the macros for PLIC driver using to calculate the offset of hart context id. Here also create a new function that PLIC driver can get the own machine mode context id to claim and complete own region.
=> Support multi-core of PLIC driver

linker_script/sections/uninit_group.c++
Increment instead of assign to allocate space for multiple stacks.
=> Properly offset the location counter to allocate multiple stacks

metal_header/sifive_test0.c++
Without this fix, the metal.h output did not work with the qemu-sifive-u54 bsp.
Now this generator looks and behaves as the others for base and size.
=> Fixing generation of base and size defs for test0

multilib.h++
Now that our toolchain supports atomics with imaf, don't perform the remapping to imf.
=> Don't remap imaf ISA to imf

multilib.h++
As long as we can determine the ABI from the ISA string, pass it through.
=> Remove multilib remapping

linker_script/sections/uninit_group.c++
let linker script support maximal-heap-size which use rest of ram as heap.
This is an optional functionality only work when "-Xlinker --defsym=__heap_max=1" is passed to linker.
if __heap_size and __heap_max are defined at the same time, __heap_max will overwrite __heap_size.
please help to review & comment. thx.
=> Support maximal-heap size option

linker_script/freedom-ldscript-generator.c++
Pull in memory range selection criteria to `master` in case we want to make this selection criteria official. **DNM** until that decision is made.
Given a memory node with two address ranges listed as unnamed `reg`:
```
memory@70000000 {
device_type = "memory";
reg = <0x70000000 0x800000 0x80000000 0x80000000>;
}; 
```
This patch picks the first of the two ranges (`0x70000000-0x70800000`) instead of the last (`0x80000000-0xFFFFFFFF`).
=> Get first unnamed reg from a memory node

linker_script/freedom-ldscript-generator.c++
Backport memory range selection criteria to `v201908-branch` in case we want to make this selection criteria official for a point release. **DNM** until that decision is made.
Given a memory node with two address ranges listed as unnamed `reg`:
```
memory@70000000 {
device_type = "memory";
reg = <0x70000000 0x800000 0x80000000 0x80000000>;
}; 
```
This patch picks the first of the two ranges (`0x70000000-0x70800000`) instead of the last (`0x80000000-0xFFFFFFFF`).
=> [v19.08] Get first unnamed reg from a memory node

freedom-openocdcfg-generator.c++
Added the ability specify the protocol and authkey to the generated openocd.cfg file, and added support for the Digilent jtag tunnel (bscan).  This should allow us to provide a single openocd.cfg file supporting all protocols (and avoid future proliferation of the generated config files to handle various configuration combinations that will arise).  
[Nate, it is up to you if you want to continue to provide both jtag and cjtag variants for CLI usage (and potentially a tunnel variant when that rolls out).  Freedom Studio will use the single default openocd.cfg file for all combinations.  This branch/PR eclipses the auth_comments branch/PR.  That branch can be deleted without merging.]
**Protocol Support** 
Defaults to the protocol specified by the `-protocol` switch to the script generator …
=> Parameterizing the generated openocd.cfg file

linker_script/sections/uninit_group.c++
Origin maximal-heap size will cause sbrk function relocation truncated to fit error 
when linker script has huge ram.
we add a heap_size upper bound to fix this. 
This modification only affect when __heap_max is defined.
please help to review & comment.
Thx
=> Fix maximal-heap size  cause relocation error

freedom-openocdcfg-generator.c++
Separates connection type out '-c set protocol' into '-c set connection' to match how Freedom Studio lets the user choose both protocol and connection.  Backward compatible with previous releases by defaulting to 'jtag' and 'olimex' when not specified on the openocd command line.  
This should go into 2019.11
=> Parameterized openocd updates

bare_header/device.c++, bare_header/device.h, bare_header/sifive_rtc0.h, bare_header/sifive_wdog0.h, metal_header/sifive_wdog0.c++
Includes some changes to allow `Device::emit_compat()` and `Device::emit_offset()` in the bare_header generator to accept a compatible string override.
=> sifive,wdt0 is another compatible string for sifive,wdog0

linker_script/sections/uninit_group.c++
Ensure SP (stack pointer) is 64 bits aligned in the generated linker files and crt0.S for MC
=> ESAT-213 fix

metal_header/sifive_uart0.c++
Other device drivers appear to declare interrupt parents for all
instances of a given type. Change the sifive_uart0 header generation
to emit definitions for all devices instead of just the first one.
https://sifive.atlassian.net/browse/ST-76
Signed-off-by: Keith Packard <keithp@keithp.com>
=> Define interrupt parent for all UART devices

metal_header/sifive_local_external_interrupts0.c++, metal_header/sifive_local_external_interrupts0.h
The local external interrupt handles are never used, and when a target has multiple local external interrupt nodes, this code generates multiple identical macros which causes compile warnings:
```
./metal/machine.h:1335: warning: "__METAL_DT_SIFIVE_LOCAL_EXINTR0_HANDLE" redefined
#define __METAL_DT_SIFIVE_LOCAL_EXINTR0_HANDLE (&__metal_dt_local_external_interrupts_1.irc)
./metal/machine.h:1330: note: this is the location of the previous definition
#define __METAL_DT_SIFIVE_LOCAL_EXINTR0_HANDLE (&__metal_dt_local_external_interrupts_0.irc)
```
Since these are private, we can safely remove this without breaking API.
=> Remove handles for local external interrupts

.github/workflows/wake.yml, build.wake, tests/test-wake-install.sh
`installFreedomDevicetreeTools` allows wake flows to install the source code for Devicetree Tools in customer deliveries and exclude all content which does not directly contribute to the generation of customer BSP content.
=> Add wake target for installing Devicetree Tools sources

build.wake
`installIn` is defined as 
```
export def installIn dir file =
installAs "{dir}/{file.getPathName}" file
```
When used with Wit, the `getPathName` would include only the repository name, for example:
```
installIn "builddir" pathToSomeFile -> builddir/freedom-devicetree-tools/somefile.sh
```
When the wake rule is used via git submodules a longer path is inserted, for example
```
installIn "builddir" pathToSomeFile -> builddir/freedom-e-sdk/software/freedom-devicetree-tools/somefile.sh
```
This PR aims to resolve the inconsistency by using `here/..` to capture the repository name directly, thus preserving the paths in `builddir`
=> Use wake 'here' to make install path source location flexible

bare_header/fixed_clock.h, fdt.c++, metal_header/fixed_clock.c++
This intends to fix ESAT-360. Invalid parsing of dts file cause invalid definition of METAL_FIXED_CLOCK__CLOCK_FREQUENCY (which is in fact due to multiple redefinition).
=> [ESAT-360]: fix issue on clock frequency multiple redefinition

metal_header/device.c++, metal_header/memory.c++
- Using `__asm__ (".weak xxx"); int xxx;` is hack way to declare a
variable is weak symbol, and clang/LLVM will emit an error for that.
=> Using attribute to declare function or variable with weak linkage.

metal_header/sifive_buserror0.c++
This prevent 'ISO C forbids empty initializer braces [-Werror=pedantic]'
error.
Signed-off-by: Frank Chang <frank.chang@sifive.com>
=> Prevent generating empty metal_buserror struct

bare_header/sifive_ccache0.h, metal_header/sifive_ccache0.c++, tests/sifive-hifive-unleashed/core.dts
We currently use ccache0 compatible in DT file of both Unleashed and Unmatched. It align with Federation, so we don't need to parse "sifive,fu540-c000,l2" anymore.
=> Remove 'fu540-c000,l2' compatible
