- fdt.h++
- freedom-mee_header-generator.c++
- tests/hifive1-mee_header.bash
- tests/hifive1.dts
With this I can get "Hello, World!" running on a HiFive1.
> Add some remaining HiFive1 support

- Makefile.am
- freedom-ldscript-generator.c++
- tests/multi-e31-arty-ldscript.bash
- tests/multi-e31-arty-makeattributes.bash
- tests/multi-e31-arty-mee_header.bash
- tests/multi-e31-arty-openocd.bash
- tests/multi-e31-arty.dts
This is a bit of a hack, but we'll have to live with it for now.
> Support designs with multiple instances of a given memory type

- freedom-ldscript-generator.c++
Previously it was population base address string. Now it use the dts field
> freedom-ldscript-generator: Corrected memory name populating

- fdt.c++
Looks like I was a bit too out of it when writing this code... :)
> Parse the third entry in compatible strings correctly

- Makefile.am
- fdt.c++
- fdt.h++
- freedom-ldscript-generator.c++
- tests/e31-memory-ldscript.bash
- tests/e31-memory-makeattributes.bash
- tests/e31-memory-mee_header.bash
- tests/e31-memory-openocd.bash
- tests/e31-memory.dts
- tests/e31-ranges-ldscript.bash
- tests/e31-ranges-makeattributes.bash
- tests/e31-ranges-mee_header.bash
- tests/e31-ranges-openocd.bash
- tests/e31-ranges.dts
Fixing U54 core linkerscript limitation
> Added memory heuristic and multiple ranges

- freedom-ldscript-generator.c++
Creates separate sections for the stack and the heap, and puts the heap above the stack.
On FPGA/dev board targets, this expands the heap to take up the remaining available memory if __heap_size != 0.
This has the following benefits:
- We can control the size of the stack and the heap independently.
- The heap can be reduced to size 0, explicitly disallowing dynamic memory allocation.
- The heap will no longer non-deterministically collide with the stack.
- This is a step towards supporting multiple stacks for SMP.
> Define separate stack and heap

- freedom-mee_header-generator.c++
Note that the `emit_include`, `emit_struct_decl`, `emit_struct_begin`, and `emit_def_handle` functions made assumptions which don't apply to the PMP driver, so it might warrant some cleanup/rethinking of the abstraction used there.
> Add mee_header generation for PMP (No vtable version)

- fdt.h++
- freedom-ldscript-generator.c++
- freedom-mee_header-generator.c++
While at it also , plus aggregate uarts interrupts
> Add machine macro check array definition

- freedom-ldscript-generator.c++
Updating linker script for specialized applications
> Utilizing itim for ramrodata

- freedom-ldscript-generator.c++
- metal_header/riscv_plic0.h
While at it also generate number of PLIC subinterrupts
> Update lds files for itim regions in .text

- freedom-makeattributes-generator.c++
- multilib.h++
Add rv32imc support and fixing to check for "rtl/arty/hifive" string instead of compare
> Makeattrib fix

- bare_header/device.c++
Signed-off-by: Nathaniel Graff <nathaniel.graff@sifive.com>
> Put a space back into the base address and size properties of bare header devices

- freedom-makeattributes-generator.c++
Make makeattributes generate the right mem width for E7 and U5 designs
> Add mem-width checks for edge cases

- bare_header/device.c++
- bare_header/device.h
Order devices of the same compatibility by base address and assign an
index starting at 0.
> Emit device base address, size, and property by index

- freedom-ldscript-generator.c++
Updated generator, based on changes proposed in https://github.com/sifive/freedom-e-sdk/pull/225
Note that now all 3 are fixed, but scratchpad and ramrodata are functionally not changed
> Keep small read-only data in flash

- freedom-makeattributes-generator.c++
The model name of unleashed is "hifive" not "hifive1" in dts file.
> Fixed update-targets.sh error of hifive-unleashed bsp.

- freedom-makeattributes-generator.c++
set iteration number for different target.
> Add Dhrystone iteration count for different target

- freedom-ldscript-generator.c++
- metal_header/riscv_cpu.h
By default, Metal will boot and run on hartid = 0.
This can be changed by specifying:
```
chosen {
metal,boothart = <&my_cpu_node>;
};
````
> Add support for metal,boothart property in chosen node

- freedom-makeattributes-generator.c++
Set iteration number for different target.
> Add coremark iteration count for different target

- Makefile.am
- freedom-makeattributes-generator.c++
Tag core series and use it for different benchmark optimization options.
> Append sifive series tags for different target.

- freedom-ldscript-generator.c++
add chicken bit into linker script generator.
For bullet series, we need to enable chicken bit to get coremark score: 4.9
> Add chicken_bit support to linker script generator

- freedom-ldscript-generator.c++
We need to split the sram when there is only one sram address in the system(E20),
otherwise, we will suffer big drop in performance.
> Split single sram address into two address spaces.

- freedom-ldscript-generator.c++
Rename finit_array to fini_array.
> Fix the typo for fini_array section name.

- build.wake
- dtc.wake
- scripts/autoconf_wrapper
Pull in files from the 'new-wake' branch to support building freedom-devicetree-tools with Wake
> Add support for Wake builds

- freedom-ldscript-generator.c++
Read the address cells and size cells of the node to determine how many
cells of the ranges table correspond to the address and size to use in
the linker script.
> Fix ldscript-generator's handling of the ranges property

- Makefile.am
- Makefile.in
- freedom-openocdcfg-generator.c++
Make the OpenOCD config generator work on 2 and 7 series cores.
> Fixes for OpenOCD Config Generator

- multilib.h++
adds
- rv32ema
- rv32ima
- rv64ima
> Add 'ma' to known ISA strings

- multilib.h++
Backport to v201905-branch corresponding to #103
> [Backport v201905] Add support for rv32emc

- freedom-ldscript-generator.c++
- freedom-openocdcfg-generator.c++
When there are two address or size cells, sum them.
> Support 2 nonzero address/size cells

- freedom-ldscript-generator.c++
- freedom-openocdcfg-generator.c++
- multilib.h++
Includes fixes for:
- Missing ISA strings
- 8-byte alignment of sections
- 2-cell sizes and addresses in ranges
> Backport recent changes from master to v201905-branch

- linker_script/strategies/default_bullet_strategy.c++
- tests/e31-memory-ldscript.bash
- tests/e31-memory.dts
DefaultBulletStrategy still needs to boot from somewhere, so look for and require a testram to match
> Add missing testram check

- metal_header/sifive_test0.c++
Pass device handle to sifive,test0 inline functions.
> Fix inline for sifive,test0

- metal_header/riscv_cpu.c++
Pull PR forward from v201908-branch
> Create IFLUSH handle for iflush API

- fdt.c++
Pulls the changes from #147 to the master branch as well.
> [Master port] Adding support for windows

- linker_script/sections/constants_group.c++
- linker_script/sections/uninit_group.c++
- Increase the default heap size to 0x800
- Fix multicore stack allocation
> Port linker script improvements from v201908 to master

- linker_script/strategies/default_e20_arty_strategy.c++
This fixes a bug which generated invalid linker script files for designs with a single sram with size <= 0x10000 bytes.
> Fix E20 Arty strategy for a single, small sram

- linker_script/strategies/default_e20_arty_strategy.c++
This fixes a bug which generated invalid linker script files for designs with a single sram with size <= 0x10000 bytes.
> [v19.08] Fix E20 Arty strategy for a single, small sram

- build.wake
remove rules for everything except the header generators
> remove wake rules for replaced tools

- Makefile.am
- Makefile.in
- bare_header/device.c++
- bare_header/device.h
- bare_header/freedom-bare_header-generator.c++
- bare_header/sifive_hca_0_5_0.h
- bare_header/sifive_hca_0_5_x.h
this merge is needed in order to support HCA 0.5.x IP under freedom metal.
> HCA 0.5.x Bare metal generator

- bare_header/sifive_hca_0_5_x.h
remove generation of METAL_SIFIVE_HCA for all platform (Not used in scl-metal)
> remove define METAL_SIFIVE_HCA

- .github/workflows/wake.yml
- tests/test-wake-install.sh
Adds a CI test for running type checking of the wake rules against the newer wake version (0.18.1)
> Add wake typecheck CI step

- bare_header/sifive_hca_0_5_x.h
DMA destination register should be @ DMA SRC + 0x08
> DMA address registers are 64-bit long

- Makefile.am
- Makefile.in
- bare_header/freedom-bare_header-generator.c++
- bare_header/sifive_remapper2.h
- metal_header/freedom-metal_header-generator.c++
- metal_header/sifive_buserror0.c++
- metal_header/sifive_remapper2.c++
- metal_header/sifive_remapper2.h
Add support for SiFive TileLink Address Remapper
> Add support for SiFive TileLink Address Remapper

- Makefile.am
- Makefile.in
- bare_header/freedom-bare_header-generator.c++
- bare_header/sifive_l2pf1.h
- metal_header/freedom-metal_header-generator.c++
- metal_header/sifive_l2pf1.c++
- metal_header/sifive_l2pf1.h
Add Stride Prefetcher (SPF) device tree node support
> Add Stride Prefetcher (SPF) device tree node support

- bare_header/sifive_l2pf0.h
- bare_header/sifive_l2pf1.h
- metal_header/sifive_l2pf0.c++
- metal_header/sifive_l2pf0.h
- metal_header/sifive_l2pf1.c++
- metal_header/sifive_l2pf1.h
https://sifive.atlassian.net/browse/ESAT-393
> Only emit the highest supported version of L2PF definition

- Makefile.am
- Makefile.in
- bare_header/freedom-bare_header-generator.c++
- bare_header/sifive_prci0.h
- metal_header/freedom-metal_header-generator.c++
- metal_header/sifive_prci0.c++
- metal_header/sifive_prci0.h
This PRCI is for SiFive HiFive platform. It basically supports getting the base address and size.
> Add support for sifive,prci0
